postgres:
  restart: always
  image: kartoza/postgis 
  ports:
    - "127.0.0.1:5432:5432"
  
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASS: postgres
    POSTGRES_DBNAME: dev
  
  volumes:
    - ./db-create.pgsql:/docker-entrypoint-initdb.d/1-db.sql
    - ./schema.pgsql:/docker-entrypoint-initdb.d/2-schema.sql
    - ./postalcodes.pgsql:/docker-entrypoint-initdb.d/3-postalcodes.sql
    - ./real-data.pgsql:/docker-entrypoint-initdb.d/4-real.sql
    - ./test-data.pgsql:/docker-entrypoint-initdb.d/5-test.sql
