postgres:
  restart: always
  image: kartoza/postgis 
  ports:
    - "127.0.0.1:5432:5432"
  
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASS: postgres
    POSTGRES_DBNAME: dev
  
  volumes:
    - ./00 db-create.pgsql:/docker-entrypoint-initdb.d/00-db.sql
    - ./10 tables.pgsql:/docker-entrypoint-initdb.d/10-db.sql
    - ./20 views.pgsql:/docker-entrypoint-initdb.d/20-db.sql
    - ./30 postalcodes.pgsql:/docker-entrypoint-initdb.d/30-db.sql
    - ./31 real-data.pgsql:/docker-entrypoint-initdb.d/40-db.sql
    - ./dev/80 test-data.pgsql:/docker-entrypoint-initdb.d/55-db.sql
