name: RDS

on:
  push:
    paths:
      - backend/rds/**
    branches: [ master ]
#  pull_request:
#    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 12.x
      uses: actions/setup-node@v1.4.4
      with:
        node-version: 12.x

    - name: Install dependencies
      run: |
        npm install
      working-directory: backend/rds

    - name: Deploy to stage
      run: |
        npx serverless deploy --stage prod
      working-directory: backend/rds
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        RDS_PASSWORD: ${{ secrets.RDS_PASSWORD }}
